name: Update Twitch Trending
on:
  schedule:
    - cron: "0 7 * * *"   # (예시) 매일 16시 KST(=7시 UTC)
  workflow_dispatch:
jobs:
  update-twitch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          pip install requests
          python update_twitch.py
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Twitch Trending" || echo "No changes to commit"
          git push
